In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0112, 0.7543, 0.5331],
        [0.7008, 0.1006, 0.8231],
        [0.8702, 0.7422, 0.9026],
        [0.7461, 0.1082, 0.5636],
        [0.0832, 0.8920, 0.3741]])


In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[-0.4285,  0.7730,  1.0780],
        [-0.8579, -0.6263,  1.0329],
        [-0.0929, -0.0418, -1.3040],
        [-0.2325,  0.3496, -0.5838],
        [ 0.1014,  0.4029, -1.5956]])


In [9]:
print(x.size())

torch.Size([5, 3])


`torch.Size`는 `tuple`타입으로, 모든 tuple 연산 지원

## 연산(Operations)

In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3130,  1.4060,  1.9116],
        [-0.6848, -0.1335,  1.6822],
        [ 0.3781,  0.4677, -0.9213],
        [-0.0886,  0.5257, -0.2214],
        [ 0.2663,  1.3026, -0.9812]])


In [11]:
print(torch.add(x, y))

tensor([[ 0.3130,  1.4060,  1.9116],
        [-0.6848, -0.1335,  1.6822],
        [ 0.3781,  0.4677, -0.9213],
        [-0.0886,  0.5257, -0.2214],
        [ 0.2663,  1.3026, -0.9812]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 0.3130,  1.4060,  1.9116],
        [-0.6848, -0.1335,  1.6822],
        [ 0.3781,  0.4677, -0.9213],
        [-0.0886,  0.5257, -0.2214],
        [ 0.2663,  1.3026, -0.9812]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.3130,  1.4060,  1.9116],
        [-0.6848, -0.1335,  1.6822],
        [ 0.3781,  0.4677, -0.9213],
        [-0.0886,  0.5257, -0.2214],
        [ 0.2663,  1.3026, -0.9812]])


In [14]:
print(x[:, 1])

tensor([ 0.7730, -0.6263, -0.0418,  0.3496,  0.4029])


In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1001])
-0.10010524094104767


### NumPy 변환 (Bridge)
#### Torch Tensor를 NumPy 배열로 변환

In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy 배열을 Torch Tensor로 변환
np 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # from_numpy() method를 통해 numpy배열에서 기인했음을 확인
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
`.to` 메서드를 사용하여 tensor를 어떠한 장치로도 옮길 수 있음

In [ ]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행
# ``torch.device``를 사용하여 tensor를 GPU 안팎으로 이동
if torch.cuda.is_availa